import { getData } from "@/utils/db-queries/getData";
import Head from "next/head";

export default function Datenschutz({ fetchedData }) {
  return (
    <>
      <Head>
        <title>Datenschutzerklärung | web-craft.design</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={`min-h-[60vh] container py-10 lg:py-20 max-w-[50%] flex flex-col gap-5 text-justify`} dangerouslySetInnerHTML={{ __html: fetchedData.attributes.privacyPolicy }}></section>
    </>
  );
}

// This also gets called at build time
export async function getStaticProps() {
  //const data = await getDataBySlug("/rezensionen", params.slug);
  const data = await getData("/general-information?populate=deep");

  //console.log(data);
  // Pass post data to the page via props
  return { props: { fetchedData: data } };
}
