import Head from "next/head";
import { getData } from "@/utils/db-queries/getData";
import ReviewGrid from "@/components/reviews/ReviewGrid.js";
import BigText from "@/components/gsap/BigText.js";
import HeroBlock from "@/components/blocks/HeroBlock.js";
import LogoGrid from "@/components/blocks/LogoGrid.js";
import FeaturesSection from "@/components/blocks/FeaturesSection.js";
import TeamSection from "@/components/blocks/TeamSection.js";
import UspSection from "@/components/blocks/UspSection.js";
import BlogPosts from "@/components/blogPosts/BlogPosts.js";

const baseURL = "https://cms.web-craft.design/";

export default function Home({ fetchedData }) {
  return (
    <>
      <Head>
        <title>Home | web-craft.design</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="overflow-hidden">
        <HeroBlock data={fetchedData.attributes.hero} />

        <section className="container py-10 lg:py-20">
          <LogoGrid data={fetchedData.attributes.logoGrid} />
        </section>

        <BigText>Modernstes Techstack trifft Design</BigText>
        <section className="container py-10 lg:py-20">
          <FeaturesSection data={fetchedData.attributes.features} />
        </section>

        <BigText position="end">Lerne uns Kennen!</BigText>
        <section className="container flex flex-col py-10 lg:py-20">
          <TeamSection data={fetchedData.attributes.team} />
        </section>

        <section className="py-10 lg:py-20">
          <UspSection data={fetchedData.attributes.usp} />
        </section>

        {/* BLOG POSTS: TODO: Schnittstelle noch anpassen */}
        {fetchedData.attributes.posts && (
          <>
            <BigText>Frisch aus der Redaktion</BigText>
            <section className="container py-10 lg:py-20">
              <BlogPosts />
            </section>
          </>
        )}

        <BigText position="end">Was zufriedene Kunden sagen</BigText>
        <section className="container py-10 lg:py-20">
          <div className="flex flex-wrap lg:flex-nowrap lg:gap-8 px-8">
            <div className="min-w-full md:min-w-[25%]">
              <h2 className="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Rezensionen</h2>
              <p className="mt-6 text-lg leading-8 text-gray-600">Was zufriedene Kunden und Partner über uns berichten:</p>{" "}
            </div>
            <ReviewGrid data={fetchedData.reviews} />
          </div>
        </section>
      </main>
    </>
  );
}

// This also gets called at build time
export async function getStaticProps() {
  //const data = await getDataBySlug("/rezensionen", params.slug);
  const data = await getData("/home?populate=deep");
  const reviews = await getData("/rezensionen?sort=reviewDate:DESC");

  data.reviews = reviews;
  //console.log(data);
  // Pass post data to the page via props
  return { props: { fetchedData: data } };
}
